### ISSUE TITLE
General question short bullet points that end with period CFS manual PSG Reading Center 18.7 QS Form Scoring Notes, Medical Alert and Study by Study outlier Identification

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#109]
https://www.sleepdata.org/datasets/cfs/pages/manuals/psg-reading-center/18-07-qs-form-scoring-notes.md

General question short bullet points that end with period CFS manual PSG Reading Center 18.7 QS Form Scoring Notes, Medical Alert and Study by Study outlier Identification, general question short bullet points most likely do not need to end with period, first point does not end with period but the next three points have a period, should the periods be deleted? The next section for Outliers has period after the last bullet point "Oxygen saturation  =  0.", delete the period?
Note the period for “10 s.” is one of the abbreviations (s.) used in the manual for “seconds” we are still waiting for a consensus “sec” vs “seconds” to use throughout the manuals on the NSRR.

![image](https://cloud.githubusercontent.com/assets/16805718/12831020/34dad68e-cb60-11e5-85a1-a1156dc81b61.png)

**Comment by mrueschman** [comment]
Closed in 243eac959731cf4acb6f3b11f630a89939f7593d
