### ISSUE TITLE
Same two issues with this page (used for CHAT and SHHS) CFS page eeg-spectral-analysis

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#28]
https://www.sleepdata.org/datasets/cfs/pages/eeg-spectral-analysis.md

CFS page EEG Spectral Analysis is the same page used for CHAT and SHHS, has the same two possible corrections.  Both corrections listed in this issue: "standalone" corrected "stand-alone" as shown in the dictionary. Second correction to spell out SOF “Study  of Osteoporotic Fractures (SOF)”.

![image](https://cloud.githubusercontent.com/assets/16805718/12687392/b48e9f40-c69d-11e5-8fca-276ed74b66fc.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12687404/c2e6a39e-c69d-11e5-89bf-4f2ce22dfca0.png)

**Comment by mrueschman** [comment]
Fixed in 24ebf6d46ef5dc11a54fc99dbe62dea73793a084
