### ISSUE TITLE
Typos 3 corrections needed [one word and two numbers] CFS manuals nitric-oxide-analyzer 14.2.2 Data Collection Procedure

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#33]
https://www.sleepdata.org/datasets/cfs/pages/manuals/nitric-oxide-analyzer/14-02-data-collection.md

Typos three corrections needed [one word and two numbers] CFS manuals nitric-oxide-analyzer 14.2.2 Data Collection Procedure, step 13 “message will be displayed indication the nature” should be “message will be displayed indicating the nature”, second correction step 15 “Repeat steps 9 through 18 until 3 NO plateaus”  correct the step numbers “Repeat steps 7 through 14 until 3 NO plateaus”.  There is no step 18, need to go back to step where you instruct the participant to breath [step 9 is not correct, my guess was step 7]

![image](https://cloud.githubusercontent.com/assets/16805718/12733651/0c48d4b2-c90a-11e5-9c29-69c477ad1f81.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12733661/1945c8dc-c90a-11e5-90e1-ea9f8f3ca037.png)

**Comment by mrueschman** [comment]
Fixed in 343d80aca1dc7a42639b8f468137a4217b0789ca
