### ISSUE TITLE
Typo "auze" should be "gauze" CFS manual blood-collection-processing 3.2 equipment and supplies 3.2.2 Blood Collection Supplies

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#37]
https://www.sleepdata.org/datasets/cfs/pages/manuals/blood-collection-processing/3-02-equipment.md

Typo “auze” should be “gauze”  CFS manuals blood-collection-processing 3.2 equipment and supplies 3.2.2 Blood Collection Supplies typo “auze” should be “gauze”

![image](https://cloud.githubusercontent.com/assets/16805718/12734179/ec0a5754-c90c-11e5-95bf-7fd2d40eff9f.png)

**Comment by mrueschman** [comment]
Fixed in b49280cd42d5bce757d269f4beb66213b6a531e4
