### ISSUE TITLE
Possible typo sentence not worded correctly? CFS manuals anthro-skinfold 6.4.2 Skinfold Techniques

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#44]
https://www.sleepdata.org/datasets/cfs/pages/manuals/anthro-skinfold/6-04-02-skinfold-techniques.md

Possible typo  sentence not worded correctly? CFS manuals anthro-skinfold 6.4.2 Skinfold Techniques  last sentence, “Karen Worman will run input the information and give this data to our office for analysis.”  The wording “will run input the information” does not seem correct.  
I am not sure the best way to correct this sentence.  Maybe delete the word "run"?  "Karen Worman will  input the information and give this data to our office for analysis.”

![image](https://cloud.githubusercontent.com/assets/16805718/12752400/622778e4-c990-11e5-9427-207fd5f70253.png)

**Comment by mrueschman** [comment]
Fixed in 109e9889b357b2de236517fbca4ac6b5db21aab3
