### ISSUE TITLE
Typo "will sent" should be "will send" CFS manual bioelectrical-impedance 7.6.3 export procedure

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#45]
https://www.sleepdata.org/datasets/cfs/pages/manuals/bioelectrical-impedance/7-06-03-export-procedure.md

Typo “will sent” should be “will send” CFS manuals bioelectrical-impedance 7.6.3 export procedure, step 3 “This will sent the file to” should be “This will send the file to”

![image](https://cloud.githubusercontent.com/assets/16805718/12752596/444cdfe8-c991-11e5-9d82-3937da5e91f2.png)

**Comment by mrueschman** [comment]
Fixed in 4e4cc55a65853974005c8f6746418c9610a488cf
