### ISSUE TITLE
Typo missing word "to" CFS manual brachial-reactivity 10.9.2 Scan Preparation

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#50]
https://www.sleepdata.org/datasets/cfs/pages/manuals/brachial-reactivity/10-09-preultrasound-preparation.md

Typo missing word “to” CFS manuals brachial-reactivity 10.9.2 Scan Preparation, “will be stored increase efficiency” should be “will be stored to increase efficiency”

![image](https://cloud.githubusercontent.com/assets/16805718/12753589/c0d0a2e4-c995-11e5-8521-36b94b656a9d.png)

**Comment by mrueschman** [comment]
Fixed in 5c0611a71853a7fc65ad5a51098759ca8cae9484
