### ISSUE TITLE
General question about correction for "30sec" in SAS report 00:00 vs 00:01 CFS manual polysomnography 17.15.2 Troubleshooting

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#88]
https://www.sleepdata.org/datasets/cfs/pages/manuals/polysomnography/17-15-02-troubleshooting.md

https://www.sleepdata.org/datasets/cfs/pages/manuals/polysomnography/17-15-01-checking-outliers-procedure.md

General question about “30sec” correction in SAS report CFS manual polysomnography 17.15.2 Troubleshooting, First (or last line of the report) has string ’30 Sec’, this page has string “30sec” replaced with “00:01” but the correction shown on page 17.15.1 is “00:00”.  Mike R might know the answer to this question since he deals with the SAS report.  I am do not remember which is the correct correction for "30sec".

![image](https://cloud.githubusercontent.com/assets/16805718/12790680/728f62f0-ca71-11e5-96bd-1af3c3570d41.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12790696/8645930a-ca71-11e5-8c90-3c6a29593fd9.png)

**Comment by mrueschman** [comment]
I don't know the answer to this one since the outlier checking using this method was mostly before my time. Closing issue.
