### ISSUE TITLE
General question about the CFS did not have multiple sites CFS manual PSG Reading Center 18.5 Data Processing, 18.5.6 Scored Sleep Data

### ISSUE THREAD

**Issue by JLArnold** [nsrr/cfs-documentation#93]
https://www.sleepdata.org/datasets/cfs/pages/manuals/psg-reading-center/18-05-data-processing.md

General question about the CFS did not have multiple sites CFS manual PSG Reading Center 18.5 Data Processing, 18.5.6 Scored Sleep Data, I thought that for the Cleveland Family Study, all the studies were done in Cleveland, so there were not multiple sites like for SHHS, etc.  This page has that reports will be emailed to each site on weekly basis. This page was copied from the SHHS manual.
Cleveland Family Study should be a single site. All studies collected, scored and processed in Cleveland.

![image](https://cloud.githubusercontent.com/assets/16805718/12797126/679b5272-ca90-11e5-8104-dafd31131d20.png)

**Comment by mrueschman** [comment]
This was a copy/paste, but I'm guessing the principle still applied - QS information was emailed to site coordinator. Closing issue.
